# This is a basic workflow to help you get started with Actions

name: Run E2E tests for Magento Store Project

on: [push]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install
